# Generated by Django 5.2.11 on 2026-03-12 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('plans', '0002_remove_plan_meals_per_week_plan_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan', verbose_name='Plan Adquirido'),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio del Plan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago'),
        ),
    ]
