# Generated by Django 5.2.11 on 2026-03-12 03:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_method'),
        ('plans', '0003_alter_studentplan_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan', verbose_name='Plan Adquirido'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Inicio del Plan'),
        ),
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='Fecha de Cierre')),
                ('total_payments', models.PositiveIntegerField(verbose_name='Número de Pagos')),
                ('total_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Efectivo')),
                ('total_transfer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Transferencia')),
                ('total_card', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Tarjeta')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total General')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Cierre')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-date'],
            },
        ),
    ]
