# Generated by Django 5.2.11 on 2026-03-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='meals_per_week',
        ),
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Duración (Días)'),
        ),
    ]
