# Generated by Django 5.2.11 on 2026-03-12 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_meals_per_week_plan_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Inicio'),
        ),
    ]
