# Generated by Django 5.2.12 on 2026-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Semestre'),
        ),
    ]
