# Generated by Django 5.2.11 on 2026-03-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_career_user_phone_user_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula/ID'),
        ),
    ]
